name: hantarr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.4+223

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_database: ^10.4.0
  firebase_analytics: ^10.8.0
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  # interactive_maps_marker: ^0.0.1
  # http: ^0.13.0
  # flutter_auth_buttons: ^0.6.0
  auth_buttons: ^3.0.0
  flutter_webview_plugin: ^0.4.0
  device_info: ^2.0.3
  # jiffy: ^3.0.1
  dio: ^5.4.3+1
  google_sign_in: ^6.1.6
  #apple_sign_in: ^0.1.0 (discontined)
  the_apple_sign_in: ^1.1.1
  line_icons: ^2.0.3
  # location_permissions: ^3.0.0+1
  permission_handler: ^11.0.1
  location: ^5.0.3
  flutter_spinkit: ^5.2.1
  flutter_zoom_drawer: ^3.2.0
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  animator: ^3.3.0
  flutter_styled_toast: ^2.1.3
  package_info: ^2.0.2
  # http_parser: 3.1.4
  image_picker: ^1.0.4
  timeline_list: ^0.0.6
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  bubble_tab_indicator: ^0.1.6
  launch_review: ^3.0.1
  bot_toast: ^4.1.3
  flutter_phoenix: ^1.1.1
  auto_size_text: ^3.0.0
  flutter_secure_storage: ^8.1.0
  flutter_svg: ^1.1.6
  showcaseview: ^2.1.1
  flutter_local_notifications: ^17.1.2
  navigation_history_observer: ^1.1.1
  geocoding: ^3.0.0
  implicitly_animated_reorderable_list: ^0.4.2
  md2_tab_indicator: ^1.0.2
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0
  geolocator: ^11.1.0
  google_maps_flutter: ^2.3.0
  ################ dont touch this package
  # google_map_location_picker: ^4.1.7
 # google_map_location_picker:
 #   git:
 #     url: https://github.com/davemg3/google_map_location_picker
  
  ########################################
  sliding_up_panel: ^2.0.0+1
  timelines: ^0.1.0
  sticky_headers: ^0.3.0+2
  dropdown_search: ^5.0.6
  flutter_snake_navigationbar: ^0.6.1
  firebase_crashlytics: ^3.4.9
  version: ^3.0.2
  webview_flutter: ^4.4.2
  smooth_page_indicator: ^1.1.0
  fuzzy: ^0.4.0-nullsafety.0
  qr_flutter: ^4.1.0
  firebase_in_app_messaging: ^0.7.4+8
  firebase_dynamic_links: ^5.4.8
  url_launcher: ^6.1.11
  
  
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sample1.jpg
    - assets/backdropColor.png
    - assets/logo.jpg
    - assets/logoword.png
    - assets/logowordWhite.png
    - assets/foodIcon.png
    - assets/map.png
    - assets/foodbag.png
    - assets/orderComplete.png
    - assets/sad.png
    - assets/topUpWallet.png
    - assets/profile.png
    - assets/rider.png
    - assets/restaurant.png
    - assets/update.png
    - assets/lang.json
    - assets/present.png
    - assets/preorder_img.svg
    - assets/empty_res.svg
    - assets/warning_cart.svg
    - assets/warning.png
    - assets/address.png
    - assets/delivery.png
    - assets/p2pDelivery.svg
    - assets/food.svg
    - assets/retail.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
